apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: langfuse
  namespace: langfuse
  labels:
    ztp-modernization-factory: "true"
spec:
  to:
    kind: Service
    name: langfuse
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
